### ISSUE TITLE
Recorder Error

### ISSUE THREAD

**Issue by coxtor** [naofireblade/clear-theme#1]
Hi this is a very nice theme however, after installation I get this error in my HA-log:

`2019-12-30 23:10:20 ERROR (Recorder) [homeassistant.components.recorder.util] Error executing query: (MySQLdb._exceptions.DataError) (1406, "Data too long for column 'event_data' at row 1")
[SQL: INSERT INTO events (event_type, event_data, origin, time_fired, created, context_id, context_user_id) VALUES (%s, %s, %s, %s, %s, %s, %s)]
[parameters: ('themes_updated', '{"themes": {"clear-dark": {"lovelace-background": "center / cover no-repeat url(data:image/jpeg;base64,/9j/4AAQSkZJRgABAQEAYABgAAD/4QBmRXhpZgAATU0AKg ... (154944 characters truncated) ... lor)", "hacs-status-pending-restart": "var(--text-dark-color)", "hacs-status-pending-update": "var(--accent-color)"}}, "default_theme": "clear-dark"}', 'LOCAL', datetime.datetime(2019, 12, 30, 22, 10, 7, 375578, tzinfo=<UTC>), datetime.datetime(2019, 12, 30, 22, 10, 20, 878159), '5e4a3fe3ef5e4e6e90092e748cb04a5c', None)]
(Background on this error at: http://sqlalche.me/e/9h9h)
2019-12-30 23:10:20 ERROR (Recorder) [homeassistant.components.recorder] Error saving event: <Event themes_updated[L]: themes=clear-dark=lovelace-background=center / cover no-repeat url(data:image/jpeg;base64,/9j/4AAQSkZJRgABAQEAYABgAAD/4QBmRXhpZgAATU0AKgAAAAgABAEaAAUAAAABAAAAPgEbAAUAAAABAAAARgEoAAMAAAABAAIAAAExAAIAAAAQAAAATgAAAAAAAABgAAAAAQAAAGAAAAABcGFpbnQubmV0IDQuMS41AP/`

For some reason the recorder wants to insert the whole theme. Do you know how to exclude themes from the recorder?

**Comment by naofireblade** [comment]
Hi this occurs because of the embedded background image.

To circumvent this problem you need to download the background image and reference it in the yaml. I added instructions how to do that: https://github.com/naofireblade/clear-theme#known-problems
